name: Run Levanter Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install --upgrade "jax[cpu]==0.4.26" "jaxlib[cpu]==0.4.26"

      - name: Install Levanter from source
        run: |
          cd ..
          git clone https://github.com/stanford-crfm/levanter.git
          cd levanter
          pip install -e .
      - name: Install Haliax on top
        run: |
          # install second since levanter will install a built version of haliax
          cd ../haliax
          pip install .[dev]
      - name: Test levanter with pytest
        run: |
          cd ../levanter
          XLA_FLAGS=--xla_force_host_platform_device_count=8 PYTHONPATH=tests:src:../src pytest tests -m "not entry and not slow"
