name: Run Levanter & Haliax Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pip and uv artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: ${{ runner.os }}-pip-uv-${{ matrix.python-version }}-${{ hashFiles('**/requirements.lock', '**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-uv-${{ matrix.python-version }}-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv and sync dependencies
        run: |
          pip install uv
          uv venv .venv
          uv sync

      - name: Install Levanter and Haliax in editable mode
        run: |
          uv pip install -e .[tests]
          uv pip install -e ../haliax
          uv pip install pytest

      - name: Run pytest suite
        env:
          XLA_FLAGS: --xla_force_host_platform_device_count=8
          VIRTUAL_ENV: ${{ github.workspace }}/.venv
        run: |
          uv run pytest tests -m "not entry and not slow"
